import { Avatar, Box, Button, Paper, Stack, Typography } from '@mui/material'
import LocationOnOutlinedIcon from '@mui/icons-material/LocationOnOutlined'
import StopCircleOutlinedIcon from '@mui/icons-material/StopCircleOutlined'
import { TEAM_MEMBERS } from '../../hooks/useSharedLocations'
import { colors, gradients } from '../../theme'

export default function TeamSidebar({ name, onNameChange, people, sharing, onShare, onStop, onFocus }) {
  const avatarSx = (member) => ({ width: 30, height: 30, border: `2px solid ${colors.white}`, boxShadow: `0 2px 6px ${colors.avatarShadow}`, backgroundImage: `url(${import.meta.env.BASE_URL}avatars/team-sprite.png)`, backgroundSize: '200% 100%', backgroundPosition: member === 'Mập' ? 'left center' : 'right center' })
  return <Paper component="aside" elevation={1} sx={{ display: 'flex', flexDirection: 'column', p: 2, minHeight: 0, border: `1px solid ${colors.border}`, background: gradients.sidebar }}><Typography variant="overline" fontWeight={900} color="primary.main">NHÓM CỦA BẠN</Typography><Typography variant="caption" fontWeight={800} color="primary.main" sx={{ mt: 1 }}>Bạn là ai?</Typography><Stack direction="row" spacing={1} sx={{ mt: .75 }}>{TEAM_MEMBERS.map((member) => <Button key={member} variant={name === member ? 'contained' : 'outlined'} onClick={() => onNameChange(member)} sx={{ flex: 1, textTransform: 'none', fontWeight: 800 }}>{member}</Button>)}</Stack><Button variant="contained" color={sharing ? 'primary' : 'secondary'} onClick={sharing ? onStop : onShare} startIcon={sharing ? <StopCircleOutlinedIcon /> : <LocationOnOutlinedIcon />} sx={{ mt: 1.5, color: sharing ? colors.white : colors.primary, fontWeight: 800, textTransform: 'none' }}>{sharing ? 'Dừng chia sẻ' : 'Chia sẻ vị trí'}</Button><Box sx={{ mt: 3 }}><Typography variant="overline" fontWeight={900} color="primary.main">ĐANG HIỂN THỊ ({people.length})</Typography>{people.map((person) => <Button key={person.user_id} fullWidth onClick={() => onFocus(person)} sx={{ justifyContent: 'flex-start', gap: 1, py: 1, borderBottom: `1px solid ${colors.subtleBorder}`, borderRadius: 0, color: colors.text, fontWeight: 700, textTransform: 'none' }}><Avatar sx={avatarSx(person.display_name)} />{person.display_name}<Box component="span" sx={{ ml: 'auto', fontSize: 22, color: colors.primaryLight }}>›</Box></Button>)}</Box><Typography variant="caption" sx={{ mt: 'auto', pt: 2, color: colors.textMuted, lineHeight: 1.5 }}>Vị trí tự ẩn sau 10 phút nếu không được cập nhật. Bạn có thể dừng chia sẻ bất cứ lúc nào.</Typography></Paper>
}
